const NAME_OR_PASSWORD_IS_REQUIRED = "用户名和密码不能为空";
const NAME_ALREAD_EXISTS = "用户已存在";
const NAME_IS_NOT__EXISTS = "用户不存在";
const PASSWORD_IS_ERROR = "密码不正确";
module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRED,
  NAME_ALREAD_EXISTS,
  NAME_IS_NOT__EXISTS,
  PASSWORD_IS_ERROR,
};
