const Koa = require("koa");
const app = new Koa();
const bodyParser = require("koa-bodyparser");
const userRouter = require("../router/userRouter");
const errHandle = require("./error-handle");
app.use(bodyParser());
app.use(userRouter.routes());
app.use(userRouter.allowedMethods());
app.on("error", errHandle);
module.exports = app;
